chainweb:
  mining:
    coordination:
      enabled: true
      updateStreamTimeout: 240
      limit: 1200
      updateStreamLimit: 200
      miners:
      - account: "${MINER_PUBLIC_KEY}"
        predicate: keys-all
        public-keys:
        - ${MINER_PUBLIC_KEY}

